### ISSUE TITLE
Error when click in "Build this Application"

### ISSUE THREAD

**Issue by viniciussilverio** [bmoers/sn-cicd#10]
I'm having an error in the Node app, when click in "Build this application button".
Config:
- CentOS 7
- Virtual Box VM
- 2GB RAM
- 30GB HD
- MID server running in the same server

Error:
![image](https://user-images.githubusercontent.com/33009217/61410226-4b2af280-a8ba-11e9-8b3a-0d602a65eefe.png)

Error text: 
Unhandled rejection TypeError: Cannot read property 'match' of null
    at CICD.module.exports (/home/vjbs/int-cicd/lib/modules/project-setup.js:471:36)
    at Promise.try.then (/home/vjbs/int-cicd/lib/eb/run-module.js:75:34)
    at tryCatcher (/home/vjbs/int-cicd/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vjbs/int-cicd/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/vjbs/int-cicd/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/home/vjbs/int-cicd/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by bmoers** [comment]
can you please share the payload from sent from ServiceNow (you find it in the logs) to the CICD server?

The payload creation in ServiceNow is here
https://github.com/bmoers/sn-cicd-integration/blob/master/script_include/CiCdRun.js#L195

The convert of the ServiceNow payload to the CICD options is here
https://github.com/bmoers/sn-cicd-example-v3/blob/master/cicd.js#L324

If you uncomment line 334 & 335 you can see the converted options 
https://github.com/bmoers/sn-cicd-example-v3/blob/master/cicd.js#L344

**Comment by bmoers** [comment]
@viniciussilverio I'm not able to reproduce. Please uncomment line 273, 334 & 335 in /cicd.js and send results.
