### ISSUE TITLE
Error when click in "Build this Application"

### ISSUE THREAD

**Issue by viniciussilverio** [bmoers/sn-cicd#12]
I'm having an error in the Node app, when click in "Build this application button".
Config:
- CentOS 7
- Virtual Box VM
- 2GB RAM
- 30GB HD
- MID server running in the same server

Error:
![image](https://user-images.githubusercontent.com/33009217/61410226-4b2af280-a8ba-11e9-8b3a-0d602a65eefe.png)

Error text: 
Unhandled rejection TypeError: Cannot read property 'match' of null
    at CICD.module.exports (/home/vjbs/int-cicd/lib/modules/project-setup.js:471:36)
    at Promise.try.then (/home/vjbs/int-cicd/lib/eb/run-module.js:75:34)
    at tryCatcher (/home/vjbs/int-cicd/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vjbs/int-cicd/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/vjbs/int-cicd/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/home/vjbs/int-cicd/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vjbs/int-cicd/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by bmoers** [comment]
can you please share the payload from sent from ServiceNow (you find it in the logs) to the CICD server?

**Comment by bmoers** [comment]
@viniciussilverio I'm not able to reproduce. Please uncomment line 273, 334 & 335 in /cicd.js and send results.

**Comment by eganesh1982** [comment]
Hi,
after completing the setup of nodejs and mid server, when i try to build the application, getting the below error. can you help?
[01:48:35.102] [LOG]    [19196]  [/worker#lwLR4eV-RSALbmdVAAAA] Starting module: projectSetup
[01:48:35.105] [LOG]    [19196]  [/worker#lwLR4eV-RSALbmdVAAAA] STARTING PROMISE JOB 'projectSetup'
[01:48:35.112] [ERROR]  [19196]  [/worker#lwLR4eV-RSALbmdVAAAA] PROMISE JOB ERROR: Job 'projectSetup' { type: 'exe',
  name: 'projectSetup',
  options:
   { updateSet: '261c169d1b9c48106933fc88cc4bcb2b',
     application:
      { id: '268e9d5fdbb32300fcf417803996195e',
        name: 'CICD Test Application' },
     requestor:
      { userName: 'admin',
        fullName: 'System Administrator',
        email: 'admin@example.com' },
     atf: { updateSetOnly: false },
     git: { repository: 'x_11413_cicd_test' },
     source: { name: 'https://dev*****.service-now.com/' },
     master: { name: null },
     target: { name: null } },
  host: 'LAPTOP-JS3P7BMM',
  id: '4ef3da58-0405-4c17-8d50-87f0474dac90',
  emitter: { _events: {}, _eventsCount: 2 },
  created: 1570168115100,
  completed: null,
  workerId: '/worker#lwLR4eV-RSALbmdVAAAA',
  result: undefined,
  error: undefined } Error: Configuration Error: source server host name not defined in config.host.name
    at Promise.try (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\lib\modules\project-setup.js:198:23)
    at tryCatcher (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\method.js:39:29)
    at CICD.configure (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\lib\modules\project-setup.js:191:27)
    at CICD.module.exports (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\lib\modules\project-setup.js:497:22)
    at Promise.try.then (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\lib\eb\run-module.js:75:34)
    at tryCatcher (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ganes\Desktop\sn-cicd-master\sn-cicd-master\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
