### ISSUE TITLE
Deployment to target breaks with - Remote update-set not found 

### ISSUE THREAD

**Issue by nci-snow-cicd** [bmoers/sn-cicd#44]
The pipeline was working fine between both my instances -now it is breaking with Remote update-set not found exception at the deployment stage; It's failing for existing applications and also for applications created from scratch,

What is the reason behind this exception? How can we fix it?

workerId: '/worker#zpr5LetrJJeqMv9yAAAB',
  result: 'BACKGROUND-JOB-IN-PROGRESS',
  error:
   { StatusCodeError: 400 - {"error":{"detail":"","message":"Remote update-set not found with \"remote_sys_id\" 3f2434266a5a6800d7ae05b98e08b293"},"status":"failure"}
       at new StatusCodeError (C:\Users\user1\Documents\sncicd-server\node_modules\request-promise-core\lib\errors.js:32:15)
       at Request.plumbing.callback (C:\Users\user1\Documents\sncicd-server\node_modules\request-promise-core\lib\plumbing.js:104:33)
       at Request.RP$callback [as _callback] (C:\Users\user1\Documents\sncicd-server\node_modules\request-promise-core\lib\plumbing.js:46:31)
       at Request.self.callback (C:\Users\user1\Documents\sncicd-server\node_modules\request\request.js:185:22)
       at Request.emit (events.js:198:13)
       at Request.<anonymous> (C:\Users\user1\Documents\sncicd-server\node_modules\request\request.js:1154:10)
       at Request.emit (events.js:198:13)
       at Gunzip.<anonymous> (C:\Users\user1\Documents\sncicd-server\node_modules\request\request.js:1076:12)
       at Object.onceWrapper (events.js:286:20)
       at Gunzip.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1145:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     name: 'StatusCodeError',
     statusCode: 400,
     message:
      '400 - {"error":{"detail":"","message":"Remote update-set not found with \\"remote_sys_id\\" 3f2434266a5a6800d7ae05b98e08b293"},"status":"failure"}',
     error: { error: [Object], status: 'failure' },
     options:
      { json: true,
        baseUrl: null,
        gzip: true,
        encoding: 'utf8',
        headers: [Object],
        jar: false,
        rawResponse: true,
        autoPagination: true,
        retry: 1,
        delay: 100,
        auth: [Object],
        followRedirect: false,
        method: 'POST',

**Comment by bmoers** [comment]
Seem so be related to Orlando on the source.
I'll setup a test env and come back

**Comment by nci-snow-cicd** [comment]
hello; wondering If you were able to reproduce the issue?

**Comment by bmoers** [comment]
I replied to your email.

> Hi 
> 
> I replayed the whole /api/devops/cicd/source/sys_update_set.do stack from here https://github.com/bmoers/sn-cicd/tree/master/doc/proxy on an Orlando Instance and it all worked fine.
> I’m unfortunately not able to reproduce the issue.
> 
> Can you please check the role of the devops user is admin?
> 
> User role check from CiCdSource.js
> 
>    checkAccess: function () {
>        if (gs.getUser().getRoles().contains('admin'))
>            return;
> 
>        if (!gs.getUser().getRoles().contains('cicd_integration_user'))
>            throw Error('User Not Authorized');
> 
>    },
> 
> Also were any ACL introduced or any other changes made on the SOAP API properties?
> 
> Regards
> Boris

**Comment by bmoers** [comment]
@nci-snow-cicd were you able to solve this issue? (I wrote you an email a while ago)

**Comment by nci-snow-cicd** [comment]
No not yet; I wasn't able to do any further testing as all environments are going through upgrade now and had to remove the pipeline from all environments. Once I have at least 2 environments back; I will redeploy everything from scratch along with a new Orlando Mid server rather than an upgraded one and see. Let's close this issue for now as I don't have a schedule yet as to when things will be ready for me to get back with deployments; and if it pops up again I will let you know.

**Comment by bmoers** [comment]
Thanks!
